use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :dndgame, Dndgame.Endpoint,
  server: true,
  root: ".",
  version: Application.spec(:phoenix_distillery, :vsn),
  url: [host: "dndgame.cstransky.me", port: 443],
#  http: [:inet6, port: {:system, "PORT"}],
  force_ssl: [hsts: true],
  cache_static_manifest: "priv/static/cache_manifest.json",
  https: [
    :inet6,
    port: {:system, "PORT"},
    cipher_suite: :strong,
    keyfile: "/etc/letsencrypt/live/dndgame.cstransky.me/privkey.pem",
    certfile: "/etc/letsencrypt/live/dndgame.cstransky.me/fullchain.pem"
  ]

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :dndgame, DndgameWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         :inet6,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :dndgame, DndgameWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases (distillery)
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :dndgame, DndgameWeb.Endpoint, server: true
#
# Note you can't rely on `System.get_env/1` when using releases.
# See the releases documentation accordingly.

# Finally import the config/prod.secret.exs which should be versioned
# separately.
get_secret = fn name ->
  base = Path.expand("~/.config/dndgame")
  File.mkdir_p!(base)
  path = Path.join(base, name)
  unless File.exists?(path) do
    secret = Base.encode16(:crypto.strong_rand_bytes(32))
    File.write!(path, secret)
  end
  String.trim(File.read!(path))
end

config :dndgame, DndgameWeb.Endpoint,
  secret_key_base: get_secret.("key_base");

# Configure your database
config :dndgame, Dndgame.Repo,
  username: "dndgame",
  database: "dndgame_prod3",
  password: "TODO_GET_PASSWORD_LOCALLY",
  pool_size: 15
